language: ruby

before_script:
  - bundle install
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create db:migrate

bundler_args: --without development --jobs=3 --retry=3

cache: bundler

env:
  matrix:
    - CI_ORM=active_record CI_DB_ADAPTER=sqlite3

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1

services:
  - mongodb

sudo: false

matrix:
  include:
    - rvm: 2.1
      env: RAILS_VERSION=4.2 CI_ORM=active_record CI_DB_ADAPTER=sqlite3
    - rvm: 2.1
      env: CI_ORM=active_record CI_DB_ADAPTER=mysql2
    - rvm: 2.1
      env: CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres
    - rvm: 2.1
      env: RAILS_VERSION=4.0 CI_ORM=active_record CI_DB_ADAPTER=sqlite3
  fast_finish: true
